title: Yeshvanth H J
logo: /assets/img/logo.png

description: I' working on the Data science, Big Data, machine learning & NLP related Problems and Data Analytics & Working on visulation tools like Power BI, Cognos BI.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
